// iv-4：前端经验总结复盘/code/react-demo/src/components/HeartBeat.js
import { useEffect } from 'react'

function HeartBeat() {
    useEffect(() => {
        let timer = 0
        function fn() {
            console.log('hello')
            timer = setTimeout(fn, 1000) // “心跳”尽量避免使用 setInterval ，有坑
        }
        timer = setTimeout(fn, 1000)

        return () => {
            clearTimeout(timer) // 组件销毁时，一定清除定时器
        }
    })

    return <p>心跳</p>
}

export default HeartBeat

// iv-4：前端经验总结复盘/code/vue3-demo/src/components/HeartBeat.vue
<template>
  <div>
    <p>心跳</p>
  </div>
</template>

<script>
import { ref, onMounted, onBeforeUnmount } from 'vue'
export default {
  name: 'HeartBeat',
  setup() {
      const timerRef = ref(0)

      onMounted(() => {
          function fn() {
              console.log('hello')
              timerRef.value = setTimeout(fn, 1000) // “心跳”尽量避免用 setInterval 会有坑
          }
          timerRef.value = setTimeout(fn, 1000)
      })

      onBeforeUnmount(() => {
          console.log('destroy')
          clearTimeout(timerRef.value) // 组件销毁时，一定清除定时器
      })
  }
}
</script>
